<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 2 / NOTE 1*

# 📝 Assignment

In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 34 not upgraded.
Need to get 9,604 kB of archives.
After this operation, 29.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 fonts-nanum all 20170925-1 [9,604 kB]
Fetched 9,604 kB in 2s (5,523 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletyp

In [ ]:
#barplot 한글 깨짐 해결을 위한 한글 폰트 불러오기
import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic')
plt.rc('axes', unicode_minus=False)

# 가설 검정

## 1. One-Sample T-test 연습

### 데이터 불러오기
- [서울시 가로수 데이터셋](https://data.seoul.go.kr/dataList/367/S/2/datasetView.do)을 사용합니다.

다음 링크를 참조하세요. 
<https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/seoul_tree/seoul_tree.txt>


In [ ]:
#데이터 셋 불러오기

import pandas as pd
import numpy as np
trees = pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/seoul_tree/seoul_tree.txt', sep = '\t', skiprows = 1, thousands = ',')
trees = trees.replace({'-':0})

trees

기간      자치구   노선수      수량    은행나무  ...    무궁화    소나무   목련   이팝나무      기타
0   2019      서울시  1412  307351  108050  ...  2,374  4,539  378  20088  20,112
1   2019      종로구    70    7329    4072  ...      0    239    0    711      29
2   2019       중구    48    8250    3640  ...     46  2,162    0    470     817
3   2019      용산구    39    7835    4444  ...      0     51  126    198     780
4   2019      성동구    38    8120    1090  ...      0     53    0    709     646
5   2019      광진구    28    7223    1247  ...      0     20  113    760     443
6   2019     동대문구    43   10664    3749  ...      1      0    0   1176     456
7   2019      중랑구    57    8365    2774  ...    212     64    0    449   1,156
8   2019      성북구    78    8449    2722  ...      5     97    0    853     547
9   2019      강북구    31    7789    3510  ...      0  1,007    0    575     410
10  2019      도봉구    63    9572    4914  ...    214     15    0     47   1,070
11  2019      노원구    50   14489    6505  ...    150     32    1    142   1,135
12  2019      은평구    35    9880    4324  ...      3      0    0    443     582
13  2019     서대문구    39    8627    3474  ...     70      0    0    493   1,120
14  2019      마포구    92   14538    3353  ...      0    124   93   1280     348
15  2019      양천구    69   13501    5622  ...    197      0    0    784     595
16  2019      강서구    55   13719    3977  ...     59    282    0   1426     568
17  2019      구로구    81   11548    3594  ...      0     30   26   1082   1,210
18  2019      금천구    30    6603    3545  ...      0      5    0    184      69
19  2019     영등포구   114   18220    5879  ...      0     40   19   1281     651
20  2019      동작구    29    7083    2178  ...    206      7    0    397     794
21  2019      관악구    32   10154    2280  ...  1,120     59    0    249   1,194
22  2019      서초구    56   16548    3800  ...     91      0    0    446   1,143
23  2019      강남구    60   23349    7210  ...      0      0    0    768     913
24  2019      송파구    99   22858   11894  ...      0    215    0   1651     450
25  2019      강동구    66   17152    5474  ...      0      0    0    642   1,969
26  2019  공원녹지사업소     1     236     179  ...      0      0    0      4       0
27  2019   시설관리공단     9   15250    2600  ...      0     37    0   2868   1,017

[28 rows x 24 columns]

### "서울시에는 구별로 평균 약 400 그루 정도의 `이팝나무`가 있다"라는 가설에 대해 가설검정을 시행하세요.

- 단, `서울시`, `공원녹지사업소`, `시설관리공단` 부분의 데이터는 제외합니다.
- 가설검정 결과의 pvalue 값을 `pv1`에 저장하세요. (`.pvalue` 사용)

In [ ]:
#서울시, 공원녹지 사업소, 시설관리공단 데이터 제외
tr = trees['자치구'].isin(['서울시', '공원녹지사업소', '시설관리공단'])
trees = trees[~tr]
#이팝나무 데이터 도출 및 평균
tree1 = trees['이팝나무']
tree1.mean()

688.64

In [ ]:
#귀무가설: 서울시에는 구별로 평균 약 400 그루 정도의 이팝나무가 있다
#가설 검정
from scipy import stats
print(stats.ttest_1samp(tree1, 400))

Ttest_1sampResult(statistic=3.3809205562101288, pvalue=0.002470712850935819)


In [ ]:
#Pvalue 저장
#귀무가설은 틀렸다
pv1 = stats.ttest_1samp(tree1, 400).pvalue
pv1

0.002470712850935819

### 이번에는 10개의 구를 샘플링하여, 위에 대한 가설검정을 다시 한번 시행해보세요.

- 단, 아래의 코드를 참조하여 sample을 위한 seed 는 123로 설정하세요.
- 가설검정 결과의 pvalue값을 `pv2`에 저장하세요


In [ ]:
import numpy as np
np.random.seed(123)

rd = np.random.choice(tree1, size = 10)
rd

array([1280,  198,  198,  449,  184,  397,  142,  768,  470,  711])

In [ ]:
print(stats.ttest_1samp(rd, 400))

Ttest_1sampResult(statistic=0.706555193453698, pvalue=0.49772576203804575)


In [ ]:
pv2 = stats.ttest_1samp(rd, 400).pvalue
pv2

0.49772576203804575

## 2. Two-Sample T-test 연습

### "서울시의 구별 평균 느티나무수와 왕벚나무의 수는 차이가 없다"라는 가설에 대해 가설검정을 시행하세요.

- 단, `서울시`, `공원녹지사업소`, `시설관리공단` 부분의 데이터는 제외합니다.
- 가설검정 결과의 pvalue를 `pv3`에 저장하세요

In [ ]:
tr = trees['자치구'].isin(['서울시', '공원녹지사업소', '시설관리공단'])
trees = trees[~tr]
t1 = trees['느티나무']
t2 = pd.to_numeric(trees['왕벚나무'].str.replace(',',''))

print(t1.head())
print(t2.head())

1     619
2     460
3     373
4    1975
5    1057
Name: 느티나무, dtype: int64
1    421
2    289
3    262
4    602
5    940
Name: 왕벚나무, dtype: int64


In [ ]:
t1.mean(), t2.mean()

(1415.12, 1292.0)

In [ ]:
#분산 확인 = 결과>0.1 므로 분산 동일
res = stats.levene(t1,t2).pvalue
res

0.4319252158673391

In [ ]:
#귀무가설은 맞다 
pv3 = stats.ttest_ind(t1,t2, equal_var = True).pvalue
pv3

0.6455096880085703


### Two-Sample One-tailed test를 사용하여 **평균 느티나무수가 왕벚나무 수보다 크다**라는 가설에 대한 가설검정을 시행하세요.
- 해당 가설검정의 결과를 `ans`에 저장하세요.

이 때 `ans`가 가질 수 있는 값은 아래와 같습니다 :
1. "느티나무" ( 느티나무의 수가 통계적으로 유의하게 많은 경우 )
2. "왕벚나무" ( 왕벚나무의 수가 통계적으로 유의하게 많은 경우 )
3. "없음" (통계적으로 유의하지 않은 경우)

다음 링크를 참조하세요.
<https://stackoverflow.com/questions/15984221/how-to-perform-two-sample-one-tailed-t-test-with-numpy-scipy>

In [ ]:
t1.mean(), t2.mean()

(1415.12, 1292.0)

In [ ]:
!pip install --upgrade scipy

In [ ]:
from scipy.stats import ttest_ind  

# Two-Sample One-tailed test
def t_test(x,y,alternative='both-sided'):
    double_p = ttest_ind(x,y,equal_var = False).pvalue
    if alternative == 'both-sided':
        pval = double_p
    elif alternative == 'greater':
        if np.mean(x) > np.mean(y):
            pval = double_p/2.      #one tail이므로 2로 나누어준다
        else:
          pval = 1.0 - double_p/2.
    elif alternative == 'less':
        if np.mean(x) < np.mean(y):
            pval = double_p/2.
        else:
            pval = 1.0 - double_p/2.
    return pval

In [ ]:
#ans 구하기
t1 = trees['느티나무']
t2 = pd.to_numeric(trees['왕벚나무'].str.replace(',',''))
if t_test(t1,t2,alternative = 'greater') > 0.5:
  print('왕벚나무')
elif t_test(t2,t1,alternative ='less') > 0.5:
  print('느티나무')
else:
  print('없음')

없음


In [ ]:
ans = 3

## 🔥 **도전과제**
> 3문제 모두 하면 됩니다.



### 1. Compare mean for multiple-sample 
 
다음 링크를 참조하세요. <https://reneshbedre.github.io/blog/anova.html>

구별, 은행나무, 양버즘나무, 느티나무에 대해서 ANOVA Test를 실행하세요.

단, `서울시`, `공원녹지사업소`, `시설관리공단` 부분의 데이터는 제외합니다.

In [ ]:
from scipy.stats import f_oneway
from scipy.stats import ttest_1samp
import matplotlib.pyplot as plt
import seaborn as sns
tr = trees['자치구'].isin(['서울시', '공원녹지사업소', '시설관리공단'])
trees = trees[~tr]

In [ ]:
trees_melt = pd.melt(trees.reset_index(), id_vars=['자치구'], value_vars = ['은행나무','양버즘나무','느티나무'])
sns.boxplot(x='자치구', y='value', hue='variable', data=trees_melt, palette='Set3')
sns.set(rc={'figure.figsize':(20,8)}, font_scale=1.5, style='whitegrid')

In [ ]:
ax = sns.boxplot(x='variable', y='value', data=trees_melt, color='#99c2a2')
ax = sns.swarmplot(x='variable', y="value", data=trees_melt, color='#7d0013')

In [ ]:
import scipy.stats as stats

fvalue, pvalue = stats.f_oneway(trees['은행나무'], trees['양버즘나무'], trees['느티나무'])
print(fvalue, pvalue)

17.006289557888046 8.935183167883698e-07


In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols('value ~ C(variable)', data = trees_melt).fit()
annova_table = sm.stats.anova_lm(model, typ=2)
annova_table

#P.value는 8.935183e-07으로 구별 나무간의 격차가 있다는 결과 도출

sum_sq    df         F        PR(>F)
C(variable)  9.990817e+07   2.0  17.00629  8.935183e-07
Residual     2.114920e+08  72.0       NaN           NaN

### 2. Sampling

- 세션 시간에 배웠던 4가지 sample 방식을 구현해보세요.

- 이를 위한 데이터는 1 부터 100 이며, sampling해야 하는 수는 20개 입니다.

- Stratified random sampling을 위한 그룹을 나누는 기준은 1-10, 11-20, ... 과 같은 방식입니다.

- Cluster sampling 을 위한 그룹을 나누는 기준은 5로 나눴을때의 나머지 값입니다. (0,1,2,3,4)

In [ ]:
import pandas as pd
import numpy as np
sample = pd.DataFrame(columns=["count"])
sample.loc[:,"count"] = np.arange(101) 
sample = sample.iloc[1:]
sample

count
1        1
2        2
3        3
4        4
5        5
..     ...
96      96
97      97
98      98
99      99
100    100

[100 rows x 1 columns]

In [ ]:
#simple random sampling
data = np.random.randint(0,100,20)
data

array([99, 67, 65,  7, 70, 99, 97, 39, 82, 92, 38,  5,  9, 40, 68, 87, 21,
       89, 50, 36])

In [ ]:
#systematic sampling
data = pd.DataFrame(sample)
def systematic_sampling(data, step):
    indexes = np.arange(0,len(data), step=step)
    systematic_sample = data.iloc[indexes]
    return systematic_sample

systematic_sample = systematic_sampling(data, 5)
print(systematic_sample)
systematic_sample.shape

    count
1       1
6       6
11     11
16     16
21     21
26     26
31     31
36     36
41     41
46     46
51     51
56     56
61     61
66     66
71     71
76     76
81     81
86     86
91     91
96     96


(20, 1)

In [ ]:
sample.groupby('count', group_keys=False).apply(lambda x: x.sample(min(len(x), 10)))


count  rest
1        1     1
2        2     2
3        3     3
4        4     4
5        5     0
..     ...   ...
96      96     1
97      97     2
98      98     3
99      99     4
100    100     0

[100 rows x 2 columns]

In [ ]:
#Cluster Sampling
sample['rest'] = sample['count']%5
sample

sample['Cluster_id'] = df.groupby 

count  rest
2      2     2
5      5     0
6      6     1
9      9     4

### 3. Data transform
다음 링크를 참조하여  `Inverse transform sampling` 을 구현합니다.

<https://youtu.be/9ixzzPQWuAY>

0 ~ 1 의 값을 동일한 확률로 갖는 `uniform distribution`으로 부터 `binomial distribution`으로 transform 하는 코드를 작성한 뒤, 두가지 결과를 시각화를 통해 비교하세요.


In [ ]:
# importing module
import numpy as np
  
  
# numpy.random.uniform() method
r = np.random.uniform(size=4)
  
# printing numbers
print(r)

[0.58256712 0.58754516 0.52437617 0.89753523]
